runtime: nodejs22
env: standard
instance_class: F1
handlers:
  - url: .*
    script: auto
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 3
  min_pending_latency: automatic
  max_pending_latency: automatic
